### PR TITLE
Add an optional dependency on jms/serializer-bundle

### PR DESCRIPTION
**Pull request by dbu**
backport https://github.com/symfony-cmf/CreateBundle/commit/894bd1c25ebf054054453564013ec0831bc8db2d as per https://github.com/Sylius/Sylius/issues/3389

### CODE REVIEW

**Comment by lsmith77** [comment]
can you also back port the memory limit fix for PHP 5.3?

**Comment by afoeder** [comment]
This breaks B/C as of

> PHP Fatal error:  Class 'JMS\SerializerBundle\JMSSerializerBundle' not found in ..../app/AppKernel.php on line 40

```
40: new JMS\SerializerBundle\JMSSerializerBundle($this)
```

Took me a while to find out what package was responsible for making the SerializerBundle vanish suddenly... What is the suggested action? Shall users add it to the project's composer.json?

**Comment by lsmith77** [comment]
yes .. sorry about that. we should have used a suggest from the beginning as there are a lot of features in this Bundle that do not require serialization

**Comment by afoeder** [comment]
So the least friction for running projects would be to put
```json
"jms/serializer-bundle": "^0.12|^1.0"
```
to the {{requires}} section in the project's root composer.json wouldn't it?

**Comment by lsmith77** [comment]
the least friction would be: ``"jms/serializer-bundle": "^0.12"``
but I would very much recommend going to ``"jms/serializer-bundle": "^1.0"`` instead and spending some extra time to validate that the update is fine

**Comment by afoeder** [comment]
:+1: thanks @lsmith77 I did the 1.0 thingie and so far it worked out well.

**Pull request merged**
